mysite/confrooms/urls.py
from django.conf.urls import patterns, url

from confrooms import views
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
   url(r'^$', views.IndexView.as_view(), name='index'),
   url(r'^book/(?P<pk>\d+)/$', login_required(views.BookView.as_view(),
                                              login_url='confrooms:index'),
       name='book'),
   url(r'^confirm/(?P<pk>\d+)/$', views.confirm, name='confirm'),
   url(r'^booking/(?P<pk>\d+)/$', login_required(views.ConfirmationView.as_view(),
                                                 login_url='confrooms:index'),
       name='booking_detail'),
   url(r'^login/$', views.login, name='login'),
   url(r'^logout/$', views.logout, name='logout'),

)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^confrooms/', include('confrooms.urls', namespace='confrooms')),
    url(r'^admin/', include(admin.site.urls)),

)

mysite/confrooms/models.py
import datetime
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models, transaction


# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=50)
    capacity = models.PositiveIntegerField()
    description = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.name

    def current_vacancies(self):
        now = datetime.datetime.now()
        return self.vacancy_set.filter(day__gte=now). \
            exclude(day=now, end_time__lte=now.hour)

    def book(self, user, day, start_time, end_time):

        if start_time >= end_time:
            return False

        vacancies = self.vacancy_set.filter(day=day, start_time__lte=start_time,
                                            end_time__gte=end_time)
        if vacancies:
            v = vacancies[0]
        else:
            return False

        with transaction.atomic():
            v.delete()
            b = Booking(room=self, user=user, day=day, start_time=start_time,
                        end_time=end_time)
            b.save()
            if v.start_time != b.start_time:
                v1 = Vacancy(room=self, day=day, start_time=v.start_time,
                             end_time=start_time)
                v1.save()
            if v.end_time != b.end_time:
                v2 = Vacancy(room=self, day=day, start_time=end_time,
                             end_time=v.end_time)
                v2.save()

        return b.pk


def validate_timespan(room, day, start_time, end_time):
    if end_time <= start_time:
            raise ValidationError('End time value cannot be lower than the start time value.')
    vacancy_set = Vacancy.objects.filter(room=room, day=day)
    vacancy_set = vacancy_set.exclude(start_time__gte=end_time).exclude(end_time__lte=start_time)
    if vacancy_set.count() > 0:
        raise ValidationError('Time span cannot overlap with any existing vacancy time span.')
    booking_set = Booking.objects.filter(room=room, day=day)
    booking_set = booking_set.exclude(start_time__gte=end_time).exclude(end_time__lte=start_time)
    if booking_set.count() > 0:
        raise ValidationError('Time span cannot overlap with any existing booking time span.')


class Vacancy(models.Model):
    room = models.ForeignKey(Room)
    day = models.DateField()
    start_time = models.IntegerField(choices=[(x, x) for x in range(0, 24)])
    end_time = models.IntegerField(choices=[(x, x) for x in range(1, 25)])

    def __unicode__(self):
        return self.room.name + " " + unicode(self.day) + ", between " + \
               unicode(self.start_time) + " - " + unicode(self.end_time)

    def clean(self):
        validate_timespan(self.room, self.day, self.start_time, self.end_time)


class Booking(models.Model):
    room = models.ForeignKey(Room)
    user = models.ForeignKey(User)
    day = models.DateField()
    start_time = models.IntegerField(choices=[(x, x) for x in range(0, 24)])
    end_time = models.IntegerField(choices=[(x, x) for x in range(1, 25)])

    def __unicode__(self):
        return self.room.name + " " + unicode(self.day) + ", between " + \
               unicode(self.start_time) + " - " + unicode(self.end_time)

    def clean(self):
        validate_timespan(self.room, self.day, self.start_time, self.end_time)

mysite/confrooms/views.py
# -*- coding: utf-8 -*-
import datetime
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from confrooms.models import Vacancy, Room, Booking


# Create your views here.
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    next_page = request.POST['next']
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        auth.login(request, user)
        return redirect(next_page)

    else:
        return render(request, 'confrooms/index.html', {
            "login_message": "Nieprawidlowe haslo lub login",
        })


def logout(request):
    auth.logout(request)
    return redirect('confrooms:index')


class IndexView(generic.ListView):
    model = Room
    template_name = 'confrooms/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        next_page = self.request.REQUEST.get('next')
        if not next_page:
            next_page = reverse('confrooms:index')
        context['next'] = next_page
        return context


class BookView(generic.DetailView):
    model = Room
    template_name = 'confrooms/book.html'

    def get_context_data(self, **kwargs):
        context = super(BookView, self).get_context_data(**kwargs)
        context['now'] = datetime.datetime.now()
        return context


@login_required(login_url='confrooms:index')
def confirm(request, pk):
    room = get_object_or_404(Room, pk=pk)
    day = request.POST['day']
    start_time = int(request.POST['start_time'])
    end_time = int(request.POST['end_time'])

    if day and start_time and end_time:
        if start_time >= end_time:
            message = "Należy podać późniejszą godzinę zakończenia niż godzina rozpoczęcia."
        else:
            try:
                book_id = room.book(user=request.user, day=day, start_time=start_time,
                             end_time=end_time)
                if book_id:
                    return redirect('confrooms:booking_detail', book_id)
                else:
                    message = "Brak wolnego terminu, wybierz inny przedział czasu."

            except IntegrityError:
                message = "Rezerwacja nie powiodła się. Sprawdź ponownie dostępne terminy."
    else:
        message = "Należy uzupełnić wszystkie pola."

    return render(request, 'confrooms/book.html', {
        'room': room,
        'message': message,
    })


class ConfirmationView(generic.DetailView):
    model = Booking
    template_name = 'confrooms/booking_detail.html'

mysite/confrooms/templates/confrooms/base.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'confrooms/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'confrooms/style.css' %}" />
    <link rel="stylesheet" href="{% static 'confrooms/css/jquery.dataTables.css' %}">
    <script src="{% static 'confrooms/js/jquery.js' %}"></script>
    <script src="{% static 'confrooms/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'confrooms/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'confrooms/js/pagination-bootstrap-plugin.js' %}"></script>
    <script src="{% static 'confrooms/js/script.js' %}"></script>

    {% block head %}{% endblock %}

    <script type="text/javascript" charset="utf-8">
    $.extend( $.fn.dataTableExt.oStdClasses, {
        "sWrapper": "dataTables_wrapper form-inline",
        "sSortAsc": "header headerSortDown",
        "sSortDesc": "header headerSortUp",
        "sSortable": "header headerSortable"
    });

    $(function() {

        $("#room-list").dataTable({
            "oLanguage": {
                "sUrl": "{% static 'confrooms/dataTables.polish.txt' %}"
            },
            "sDom": "<'row'<'col-md-6'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
            "sPaginationType": "bootstrap",
            "bAutoWidth" : false,
            "aoColumns" : [
                    { "sWidth" : "20%" },
                    { "sWidth" : "20%" },
                    { "sWidth" : "60%" },
            ],
            "bSortClasses": false
        });


    });
    </script>

    <title>{% block title %}System Rezerwacji Pokoi Konferencyjnych{% endblock %}</title>
</head>
<body>


{% if login_message %}
    <div id="login-status">
        <div class="alert alert-danger">
            <p><strong>Alert:</strong> {{ login_message }} </p>
        </div>
    </div>
{% endif %}


<div class="container">
<div id="login-form" class="pull-right">

    {% if user.is_authenticated %}
    <form action="{% url 'confrooms:logout' %}" method="POST" class="form-inline">
        {% csrf_token %}
        <label for="logout-button">Zalogowany: {{ user.username }} </label>
        <input class="btn btn-default btn-sm" type="submit" id="logout-button" value="Wyloguj">
    </form>

    {% else %}
    <form action="{% url 'confrooms:login' %}" method="POST" class="form-inline">
        {% csrf_token %}
        <div class="form-group">
            <label class="sr-only" for="login-username">Użytkownik</label>
            <input class="form-control input-sm" type="text" name="username" id="login-username" placeholder="Login">
        </div>
        <div class="form-group">
            <label class="sr-only" for="login-password">Hasło</label>
            <input class="form-control input-sm" type="password" name="password" id="login-password" placeholder="Hasło">
        </div>
        <input class="btn btn-default btn-sm" type="submit" id="login-button" value="Zaloguj">
        <input type="hidden" name="next" value="{{ next }}">
    </form>
    {% endif %}

</div>

<nav>
    <ol class="breadcrumb">
        {% block navigation %}{% endblock %}
    </ol>
</nav>
</div>

<div id="content">
    {% block content %}{% endblock %}
</div>

</body>
</html>


mysite/confrooms/templates/confrooms/book.html
{% extends "confrooms/base.html" %}

{% block navigation %}
    <li><a href="{% url 'confrooms:index' %}">Pokoje</a></li>
    <li class="active">Rezerwacja</li>
{% endblock %}


{% block content %}
<div class="container">
    <div id="room-description">
        <h2>{{ room.name }}</h2>
        <p>
            Pojemność: {{ room.capacity }}
        </p>
        <p>
            {{ room.description }}
        </p>
    </div>

    <div id="room-booking-form">
        {% if message %}


        <div class="alert alert-warning">
            <strong>Uwaga:</strong> {{ message }} </p>
        </div>

        {% endif %}
        <form class="form-inline" action="{% url 'confrooms:confirm' room.pk %}" method="post">
        {% csrf_token %}
            <div class="form-group">
                <label for="booking-day"> Data </label>
                <input class="form-control" type="date" name="day" id="booking-day" value="{{ now|date:"Y-m-d" }}">
            </div>
            <div class="form-group">
                <label for="booking-start-time"> Od </label>
                <input class="form-control" type="number" name="start_time" id="booking-start-time" min="0" max="23">
            </div>
            <div class="form-group">
                <label for="booking-end-time"> Do </label>
                <input class="form-control" type="number" name="end_time" id="booking-end-time" min="1" max="24">
            </div>
            <input class="btn btn-primary" type="submit" id="booking-button" value="Zarezerwuj">
        </form>
    </div>


    <div id="room-vacancies-list" class="panel panel-default">
        <div class="panel-heading">
                <h2 class="panel-title">Wolne terminy</h2>
        </div>
        <div class="panel-body">
        {% if room.current_vacancies %}
        <ul>
            {% for v in room.current_vacancies|dictsort:"start_time"|dictsort:"day" %}
            <li>{{ v.day|date:"d E Y" }}, godz. {{ v.start_time }}:00 - {{ v.end_time }}:00
                <span class="hidden day-field">{{ v.day|date:"Y-m-d" }}</span>
                <span class="hidden start-time-field">{{ v.start_time }}</span>
                <span class="hidden end-time-field">{{ v.end_time }}</span> </li>
            {% endfor %}
        </ul>
        {% else %}
            <div class="alert alert-info">
                <p>Brak wolnych terminów.</p>
            </div>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mysite/confrooms/templates/confrooms/booking_detail.html
{% extends "confrooms/base.html" %}

{% block navigation %}
<ol class="breadcrumb">
    <li><a href="{% url 'confrooms:index' %}">Pokoje</a></li>
    <li><a href="{% url 'confrooms:book' booking.room.pk %}">Rezerwacja</a></li>
    <li class="active">Potwierdzenie</li>
</ol>
{% endblock %}


{% block content %}
<div class="container">
    {% if user != booking.user %}

    <div class="alert alert-info">
            <p>Tylko użytkownik który dokonał rezerwacji może ją podejrzeć.</p>
    </div>

    {% else %}

    <div class="col-md-6 col-md-offset-3">
    <div id="booking-description" class="panel panel-default">
        <div class="panel-heading">
            Pomyślnie dokonano następującej rezerwacji:
        </div>
        <div class="panel-body">
            <dl class="dl-horizontal">
                <dt>Pokój</dt>
                <dd>{{ booking.room.name }}</dd>
                <dt>Pojemność</dt>
                <dd>{{ booking.room.capacity }}</dd>
                <dt>Opis</dt>
                <dd>{{ booking.room.description|truncatewords:"10" }}</dd>
                <dt>Data</dt>
                <dd>{{ booking.day|date:"d E Y" }}</dd>
                <dt>Godziny</dt>
                <dd>{{ booking.start_time }}:00 - {{ booking.end_time }}:00</dd>
            </dl>
            <div class="text-center">
            <a href="{% url 'confrooms:index' %}">
            <button name="ok" id="booking-confirmation-button" class="btn btn-info">OK</button>
            </a>
            </div>
        </div>
    </div>
    </div>

    {% endif %}
</div>
{% endblock %}

mysite/confrooms/templates/confrooms/index.html
{% extends "confrooms/base.html" %}
{% load staticfiles %}

{% block head %}

{% endblock %}


{% block navigation %}
    <li><a href="#">Pokoje</a></li>
{% endblock %}


{% block content %}


<div class="jumbotron">
    <div class="container">
    <h1>Pokoje</h1>
    <p>
        Aplikacja służąca do rezerwacji miejsc w pokojach konferencyjnych.
    </p>
    <p>
        <a href="http://www.mimuw.edu.pl/~ciebie/drupal/?q=node/3"
           class="btn btn-primary btn-lg" role="button" target="_blank">Więcej</a>
    </p>
    </div>
</div>

<div class="container">
{% if user.is_authenticated %}

    {% if object_list %}

    <table id="room-list" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nazwa</th>
                <th>Pojemność</th>
                <th>Opis</th>
            </tr>
        </thead>
        <tbody>
            {% for room in object_list %}
             <tr>
                 <td> <a href="{% url 'confrooms:book' room.pk %}">{{ room.name }}</a>
                     {% if room.current_vacancies.count > 0 %}
                      <span class="badge">{{ room.current_vacancies.count }}</span>
                     {% endif %}
                 </td>
                 <td class="text-right"> {{ room.capacity }} </td>
                 <td> {{ room.description|truncatewords:"10" }} </td>
             </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}

    <p>Brak wolnych pokoi.</p>

    {% endif %}

{% else %}

    <div class="alert alert-info">
    <p>Tylko zalogowani użytkownicy mają dostęp do systemu.</p>
    </div>

{% endif %}
</div>

{%endblock %}